
import com.healthmarketscience.jackcess.Row;
import java.awt.Button;
import java.awt.List;
import java.awt.print.PrinterException;
import static java.nio.file.Files.list;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import static java.util.Collections.list;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author moham
 */
public class Print extends javax.swing.JFrame {

    /**
     * Creates new form Print
     * 
     * 
     */
    int x=0;
    public Print() {
        initComponents();
        this.setVisible(true);
        this.setSize(1500,500);
        this.setLocationRelativeTo(null);
        jTextField8.setEditable(false);
        jTextField10.setEditable(false);
        jTextField11.setEditable(false);
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
   System.out.print("Mohammad"); }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        j1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        j3 = new javax.swing.JTextField();
        j2 = new javax.swing.JTextField();
        j4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\moham\\Desktop\\Sas3ojan\\5w4Nqx4AiCjUCajw.jpg")); // NOI18N
        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("بحث");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 40, 81, 20);

        j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1ActionPerformed(evt);
            }
        });
        getContentPane().add(j1);
        j1.setBounds(380, 40, 98, 20);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 204));
        jLabel2.setText("ادخل اسم العميل");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(520, 40, 73, 17);

        jButton2.setText("طباعة الكشف");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 400, 140, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "رقم البند", "البيان", "السعر", "الكمية", "السعر الاجمالي", "الدفعة", "المبلغ المتبقي", "تاريخ الفاتورة"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 110, 680, 260);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(0, 255, 204));
        jRadioButton1.setText("من اول تاريخ");
        jRadioButton1.setOpaque(false);
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(263, 40, 100, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(0, 255, 204));
        jRadioButton2.setText("من تاريخ معين");
        jRadioButton2.setOpaque(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(260, 70, 93, 23);

        j3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3ActionPerformed(evt);
            }
        });
        getContentPane().add(j3);
        j3.setBounds(140, 70, 30, 20);
        getContentPane().add(j2);
        j2.setBounds(80, 70, 30, 20);
        getContentPane().add(j4);
        j4.setBounds(200, 70, 50, 20);

        jLabel4.setForeground(new java.awt.Color(0, 255, 204));
        jLabel4.setText("السنة");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 90, 28, 14);

        jLabel5.setForeground(new java.awt.Color(0, 255, 204));
        jLabel5.setText("اليوم");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 90, 22, 14);

        jLabel6.setForeground(new java.awt.Color(0, 255, 204));
        jLabel6.setText("/");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 70, 20, 20);

        jLabel7.setForeground(new java.awt.Color(0, 255, 204));
        jLabel7.setText("/");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(180, 70, 10, 20);

        jLabel8.setForeground(new java.awt.Color(0, 255, 204));
        jLabel8.setText("الشهر");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(140, 90, 29, 14);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 204));
        jLabel1.setText("فرع المشيرفة");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 0, 180, 42);

        jButton5.setText("أضافة عميل جديد");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(680, 20, 130, 23);

        jButton7.setText("تعديل بند");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(700, 100, 100, 23);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel18.setForeground(new java.awt.Color(0, 255, 204));
        jLabel18.setText("اسم العميل");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(200, 10, 60, 14);

        jLabel19.setForeground(new java.awt.Color(0, 255, 204));
        jLabel19.setText("البيان");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(210, 40, 24, 14);

        jLabel20.setForeground(new java.awt.Color(0, 255, 204));
        jLabel20.setText("السعر");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(210, 70, 29, 20);

        jLabel21.setForeground(new java.awt.Color(0, 255, 204));
        jLabel21.setText("الكمية");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(210, 110, 29, 14);

        jLabel22.setForeground(new java.awt.Color(0, 255, 204));
        jLabel22.setText("التاريخ");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(210, 130, 28, 14);

        jLabel23.setForeground(new java.awt.Color(0, 255, 204));
        jLabel23.setText("المجموع");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(210, 180, 39, 14);

        jButton3.setText("حساب المجموع");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(80, 200, 140, 23);

        jLabel24.setForeground(new java.awt.Color(0, 255, 204));
        jLabel24.setText("الدفعة");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(220, 230, 29, 14);

        jLabel25.setForeground(new java.awt.Color(0, 255, 204));
        jLabel25.setText("المبلغ الباقي");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(200, 260, 59, 14);

        jButton8.setText("حساب المبلغ الباقي");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(80, 280, 140, 23);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(20, 10, 110, 30);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(20, 40, 110, 30);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(20, 70, 110, 30);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(20, 100, 110, 30);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(20, 130, 30, 20);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(60, 130, 30, 20);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(100, 130, 30, 20);
        jPanel1.add(jTextField8);
        jTextField8.setBounds(20, 180, 110, 20);
        jPanel1.add(jTextField9);
        jTextField9.setBounds(20, 230, 110, 20);
        jPanel1.add(jTextField10);
        jTextField10.setBounds(20, 260, 110, 20);

        jLabel26.setForeground(new java.awt.Color(0, 255, 204));
        jLabel26.setText("رقم البند");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(170, 370, 40, 14);
        jPanel1.add(jTextField11);
        jTextField11.setBounds(50, 360, 90, 30);

        jLabel9.setForeground(new java.awt.Color(0, 255, 204));
        jLabel9.setText("اليوم");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 150, 22, 14);

        jLabel10.setForeground(new java.awt.Color(0, 255, 204));
        jLabel10.setText("الشهر");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(60, 150, 29, 14);

        jLabel11.setForeground(new java.awt.Color(0, 255, 204));
        jLabel11.setText("السنة");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(100, 150, 28, 14);

        jButton4.setText("تم");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(130, 320, 60, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(810, 10, 270, 430);

        jButton6.setText("أضافة بند");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(700, 60, 100, 23);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 255, 204));
        jLabel12.setText("رقم البند");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(150, 30, 37, 17);
        jPanel2.add(jTextField12);
        jTextField12.setBounds(90, 20, 60, 30);
        jPanel2.add(jTextField13);
        jTextField13.setBounds(20, 70, 120, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 255, 204));
        jLabel13.setText("اسم العميل");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(154, 70, 47, 17);
        jPanel2.add(jTextField14);
        jTextField14.setBounds(20, 110, 120, 30);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 255, 204));
        jLabel14.setText("البيان");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(170, 110, 40, 20);
        jPanel2.add(jTextField15);
        jTextField15.setBounds(20, 150, 120, 30);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 255, 204));
        jLabel15.setText("الكمية");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(170, 160, 26, 17);
        jPanel2.add(jTextField16);
        jTextField16.setBounds(20, 190, 120, 30);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 255, 204));
        jLabel16.setText("السعر");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(170, 200, 26, 17);
        jPanel2.add(jTextField17);
        jTextField17.setBounds(20, 230, 30, 20);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 255, 204));
        jLabel17.setText("التاريخ");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(170, 230, 29, 17);
        jPanel2.add(jTextField18);
        jTextField18.setBounds(60, 230, 30, 20);
        jPanel2.add(jTextField19);
        jTextField19.setBounds(100, 230, 40, 20);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 255, 204));
        jLabel27.setText("اليوم");
        jPanel2.add(jLabel27);
        jLabel27.setBounds(20, 250, 20, 17);

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 255, 204));
        jLabel28.setText("الشهر");
        jPanel2.add(jLabel28);
        jLabel28.setBounds(60, 250, 26, 17);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 255, 204));
        jLabel29.setText("السنة");
        jPanel2.add(jLabel29);
        jLabel29.setBounds(100, 250, 21, 17);
        jPanel2.add(jTextField20);
        jTextField20.setBounds(20, 270, 120, 30);

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 255, 204));
        jLabel30.setText("المجموع");
        jPanel2.add(jLabel30);
        jLabel30.setBounds(160, 280, 39, 17);
        jPanel2.add(jTextField21);
        jTextField21.setBounds(20, 310, 120, 30);

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 255, 204));
        jLabel31.setText("الدفعة");
        jPanel2.add(jLabel31);
        jLabel31.setBounds(170, 320, 26, 20);
        jPanel2.add(jTextField22);
        jTextField22.setBounds(20, 350, 120, 20);

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 255, 204));
        jLabel32.setText("المبلغ الباقي");
        jPanel2.add(jLabel32);
        jLabel32.setBounds(150, 350, 60, 17);

        jButton9.setText("تم");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9);
        jButton9.setBounds(80, 380, 73, 23);

        jButton10.setText("بحث");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10);
        jButton10.setBounds(10, 20, 53, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(1090, 0, 240, 410);

        jLabel33.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 255, 204));
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/big_e38f1f8a5b65d11fc876e806ee1684f3c36d3f0f.jpg"))); // NOI18N
        jLabel33.setText("jLabel33");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(0, 0, 1400, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
           DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
model.setRowCount(0);
        Connection con;
            Statement st;
            ResultSet rs;
            try{
                 con = DriverManager.getConnection("jdbc:ucanaccess://D:/SasMsherfa/Sas.accdb");
                st=con.createStatement();
                rs=st.executeQuery("select * from info");
                    
         DefaultTableModel t=(DefaultTableModel) jTable1.getModel();
        if(jRadioButton1.isSelected()){
                    
                     
               
                while(rs.next()){
                    if(j1.getText().equalsIgnoreCase(rs.getString("name"))){
                        String[] r={rs.getInt("ID")+(""),rs.getString("desc"),rs.getDouble("price")+"",rs.getDouble("amount")+"",rs.getDouble("total")+"",rs.getDouble("pay")+"",rs.getDouble("totalall")+"",rs.getString("date")+""};
                     
                        t.addRow(r);

                              
                                System.out.println("Done");
                        }}}
        else{
            
            int x=0;
              while(rs.next()){
                  String sea=j2.getText()+"/"+j3.getText()+"/"+j4.getText();
                  
                  if(j1.getText().equalsIgnoreCase(rs.getString("name"))){
                  if(sea.equalsIgnoreCase(rs.getString("date"))||x==1){
                      x=1;
                       String[] r={rs.getInt("ID")+(""),rs.getString("desc"),rs.getDouble("price")+"",rs.getDouble("amount")+"",rs.getDouble("total")+"",rs.getDouble("pay")+"",rs.getDouble("totalall")+"",rs.getString("date")};
                     
                        t.addRow(r);

                              
                                System.out.println("Done");
                  }
              }}
        
        }
           con.close();
            }
            catch(Exception e){
                e.printStackTrace();
                        };
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void j1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            
            jTable1.print(JTable.PrintMode.FIT_WIDTH);
        } catch (PrinterException ex) {
            Logger.getLogger(Print.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void j3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jPanel1.setVisible(true);
        jPanel2.setVisible(false);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
model.setRowCount(0);
jTextField1.setEditable(true);
x=1;
jTextField1.setText("");
jTextField2.setText("");
jTextField3.setText("");
jTextField4.setText("");
jTextField5.setText("");
jTextField6.setText("");
jTextField7.setText("");
jTextField8.setText("");
jTextField9.setText("");jTextField10.setText("");jTextField11.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         jPanel1.setVisible(true);
         jPanel2.setVisible(false);
jTextField1.setText(j1.getText());
jTextField1.setEditable(false);
 x=2;
jTextField2.setText("");
jTextField3.setText("");
jTextField4.setText("");
jTextField5.setText("");
jTextField6.setText("");
jTextField7.setText("");
jTextField8.setText("");
jTextField9.setText("");jTextField10.setText("");jTextField11.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed
public void sum(){
 Connection con;
        Statement st;
        ResultSet rs;
        double d=0;
        try { 
            con = DriverManager.getConnection("jdbc:ucanaccess://D:/SasMsherfa/Sas.accdb");
            st = con.createStatement();
            rs = st.executeQuery("select * from info");
            while(rs.next()){
                if(jTextField1.getText().equals(rs.getString("name"))){
                    d=rs.getDouble("totalall");
                }
            }
            con.close();
        }
        catch(Exception e){
            e.printStackTrace();
        }
          double xx=Double.parseDouble(jTextField9.getText());
        double yy=Double.parseDouble(jTextField8.getText());
        jTextField10.setText(yy-xx+d+"");
}
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         Connection con;
       Statement st;
       ResultSet rs;
       try{
            con = DriverManager.getConnection("jdbc:ucanaccess://D:/SasMsherfa/Sas.accdb");
            st=con.createStatement();
            rs=st.executeQuery("select * from info");
            String date=jTextField5.getText()+"/"+jTextField6.getText()+"/"+jTextField7.getText();
            String query="insert into info(name,desc,price,amount,total,pay,totalall,date)"+
                                                    "values('"+jTextField1.getText()+"','"+jTextField2.getText()+"',"+jTextField3.getText()+","+jTextField4.getText()+","+jTextField8.getText()+","+jTextField6.getText()+","+jTextField10.getText()+",'"+date+"')";
            PreparedStatement ps  = con.prepareStatement(query);
            ps.executeUpdate();
             while(rs.next()){        
                jTextField11.setText(rs.getInt("ID")+1+"");
             
                  
                }
               DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
model.setRowCount(0);
            se();
            con.close();
            System.out.println("Done");
       }
       catch(Exception e){
           e.printStackTrace();
       }
       JOptionPane.showMessageDialog(this, "تم بنجاح اضافة الفاتورة");
    }//GEN-LAST:event_jButton4ActionPerformed
public void se(){
     Connection con;
       Statement st;
       ResultSet rs;
       try{
            con = DriverManager.getConnection("jdbc:ucanaccess://D:/SasMsherfa/Sas.accdb");
            st=con.createStatement();
            rs=st.executeQuery("select * from info");
            DefaultTableModel t=(DefaultTableModel) jTable1.getModel();
            while(rs.next()){
                if(jTextField1.getText().equals(rs.getString("name"))){
                String[] r={rs.getString("name"),rs.getString("desc"),rs.getDouble("price")+"",rs.getDouble("amount")+"",rs.getDouble("total")+"",rs.getDouble("pay")+"",rs.getDouble("totalall")+"",rs.getString("date"),rs.getInt("ID")+("")};
                     
                        t.addRow(r);}
            }
       
       con.close();}
       catch(Exception e){
           e.printStackTrace();
       }
}
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        double x=Double.parseDouble(jTextField3.getText());
        double y=Double.parseDouble(jTextField4.getText());
        jTextField8.setText(x*y+"");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if(x==1){
        double xx=Double.parseDouble(jTextField9.getText());
        double yy=Double.parseDouble(jTextField8.getText());
        jTextField10.setText(yy-xx+"");}
        else{
            sum();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(false);
        jPanel2.setVisible(true);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
model.setRowCount(0);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
model.setRowCount(0);
Connection con;
            Statement st;
            ResultSet rs;
            try{
                 con = DriverManager.getConnection("jdbc:ucanaccess://D:/SasMsherfa/Sas.accdb");
                st=con.createStatement();
                rs=st.executeQuery("select * from info");
             DefaultTableModel t = (DefaultTableModel) jTable1.getModel();
                    String ddd=jTextField17.getText()+"/"+jTextField18.getText()+"/"+jTextField19.getText();
             st.executeUpdate("update info set name='"+jTextField13.getText()+"',desc='"+jTextField14.getText()+"',price="+jTextField15.getText()+",amount="+jTextField16.getText()+",date='"+ddd+"',total="+jTextField20.getText()+",pay="+jTextField21.getText()+",totalall="+jTextField22.getText()+" where ID="+jTextField12.getText()+"");
             JOptionPane.showMessageDialog(this, "تم التعديل بنجاح");
             while(rs.next()){
                 if(jTextField12.getText().equals(rs.getInt("ID"))){
                String[] r={rs.getString("name"),rs.getString("desc"),rs.getDouble("price")+"",rs.getDouble("amount")+"",rs.getDouble("total")+"",rs.getDouble("pay")+"",rs.getDouble("totalall")+"",rs.getString("date"),rs.getInt("ID")+("")};
                     
                        t.addRow(r);}
             }
                     con.close();
               
            }
            catch(Exception ex){
                ex.printStackTrace();
            }
            jTextField12.setText("");
            jTextField13.setText("");
         jTextField14.setText("");
          jTextField15.setText("");
           jTextField16.setText("");
            jTextField17.setText("");
             jTextField18.setText("");
              jTextField19.setText(""); jTextField20.setText(""); jTextField21.setText(""); jTextField22.setText("");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here: 
        
              
              
              
        Connection con;
            Statement st;
            ResultSet rs;
            try{
              
                con = DriverManager.getConnection("jdbc:ucanaccess://D:/SasMsherfa/Sas.accdb");
                st=con.createStatement();
                rs=st.executeQuery("select * from info");
                int x=0;
                
                while(rs.next()){
                    if(jTextField12.getText().equalsIgnoreCase(rs.getInt("ID")+"")){
                        jTextField17.setText(rs.getString("date").substring(0,2));
                        jTextField18.setText(rs.getString("date").substring(3,5));
                       jTextField19.setText(rs.getString("date").substring(6,10));
                         jTextField13.setText(rs.getString("name"));
                        jTextField14.setText(rs.getString("desc"));
                        jTextField15.setText(rs.getDouble("price")+"");
                        jTextField16.setText(rs.getDouble("amount")+"");
                        jTextField20.setText(rs.getDouble("total")+"");
                        jTextField21.setText(rs.getDouble("pay")+"");
                        jTextField22.setText(rs.getDouble("totalall")+"");
                        JOptionPane.showMessageDialog(this,"تم ايجاد الفاتورة");
                        x=1;
                                }}
                if(x==0)
                        JOptionPane.showMessageDialog(this, "رقم الفاتورة غير موجود");
               
            }
            catch(Exception ex){
                ex.printStackTrace();
            }
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Print().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField j1;
    private javax.swing.JTextField j2;
    private javax.swing.JTextField j3;
    private javax.swing.JTextField j4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
